# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_testimagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModelWithoutFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
