# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 06:54
from __future__ import unicode_literals

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_testmodelwithoutfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimagemodel',
            name='image',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='tests-images/'),
        ),
        migrations.AlterField(
            model_name='testimagemodel',
            name='file',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='tests/'),
        ),
    ]
