# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 04:28
from __future__ import unicode_literals

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_testvideomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testvideomodel',
            name='video',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='tests-videos/', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
